### ISSUE TITLE
What Could Be The Problem.A New Host is Being Added.

### ISSUE THREAD

**Issue by ericnyamubbp** [RhinoSecurityLabs/IPRotate_Burp_Extension#37]
Hi,

When using the iprotator something strange is happeing.Itsnot on all sites though.A new host is being requested.It called 3od2hxr135.execute-api.eu-north-1.amazonaws.com .And it messing up the attack.Take a look at the screenshots

![Screenshot from 2021-08-16 15-06-25](https://user-images.githubusercontent.com/74705471/129561511-e5db0ee2-4215-43dc-8a15-2c53ab44849c.png)

![Screenshot from 2021-08-16 15-06-46](https://user-images.githubusercontent.com/74705471/129561702-4232ced6-416d-4371-bc71-a7a31c984d86.png)

![Screenshot from 2021-08-16 15-07-14](https://user-images.githubusercontent.com/74705471/129561742-228b1108-262d-47fd-9783-d349a7c0c399.png)

![Screenshot from 2021-08-16 15-07-43](https://user-images.githubusercontent.com/74705471/129561767-86d5b89d-9d8d-42bb-b641-7050de498054.png)

Is there away to remove this host from being added.

Thanks

**Comment by DaveYesland** [comment]
The host is added because when you enable the extension requests no longer are sent to the target. They are sent to the API Gateway endpoint. You could try a match and replace to change the Host header but that will probably break the way API Gateway works. I am not sure of any other fix but let me know if you figure something out.

**Comment by hishammir** [comment]
Hi @ericnyamubbp @DaveYesland  , Did you find a solution to this problem, I am having the same problem, i know the request is sent to the API gateway endpoint and it then sends a request further to the target and bring back the response.

But im not getting the desired response, the response is from the was API endpoint instead of the target.

![image](https://user-images.githubusercontent.com/30221965/189456360-c25ea1ee-8ee8-4dee-b966-8690902f1394.png)

Im using burp v2022.8.2
